### ISSUE TITLE
Вытянуть в общую табличку сайт 300

### ISSUE THREAD

**Issue by dropt22** [Crowdfunding-crypto/forum#13]
если не получиться - так и отпишись
![default](https://cloud.githubusercontent.com/assets/7222200/5561003/100d8cec-8dd2-11e4-8b9f-5b832b98f7ea.jpg)

**Comment by freepad** [comment]
Получилось

**Comment by dropt22** [comment]
сайт подписчиков(ссылка на соц.сеть) не отображается
