### ISSUE TITLE
Убираем лишнее для пользователя 400

### ISSUE THREAD

**Issue by dropt22** [Crowdfunding-crypto/forum#14]
все что выделенно красным удаляем для пользователя
![1](https://cloud.githubusercontent.com/assets/7222200/5561020/1d45a7ea-8dd3-11e4-9ec0-fe8d3c3f4ee9.jpg)

**Comment by freepad** [comment]
Лого WP убрал

**Comment by freepad** [comment]
Меню убрал
Копирайты из подвала тоже

**Comment by dropt22** [comment]
ок
