### ISSUE TITLE
Изменения в разделе форумов 600

### ISSUE THREAD

**Issue by dropt22** [Crowdfunding-crypto/forum#18]
Рассмотрим на примере раздела "Проекты"
1) Кнопка "Создать новый проект" должна переносить пользователя в конец ленты, где можно заполнить форму
2) передвинуть столбцы чтобы помещались все слова в шапке таблицы. 
3) переместить статистику в самый конец
4) убрать лишнее (Просмотр темы...)
5) еще не отметил на картинке - передвинь пожалуйста кнопку "подписаться" до конца вправо.

![default](https://cloud.githubusercontent.com/assets/7222200/5561705/c0180abe-8e03-11e4-8f99-839195328d59.jpg)

**Comment by freepad** [comment]
В столбцах заголовки не переносятся теперь на новую строку при нехватке места, появляется многоточие. 
Таблица адаптивная.
![2015-01-05 20 41 05](https://cloud.githubusercontent.com/assets/3172415/5667263/6a9c971c-9777-11e4-9754-b5784751a9ca.png)
![2015-01-05 20 46 50](https://cloud.githubusercontent.com/assets/3172415/5667272/7f56844c-9777-11e4-8298-8bdb2ca43e80.png)

**Comment by freepad** [comment]
Готово

**Comment by dropt22** [comment]
Дамир, осталось кнопку "Подписаться" подправить ( 5-ый пункт см выше ):
1) либо передвинуть ее чуть правее = вставить пробелы
2) либо перенести на новую строку через пробел
3) либо адаптивно в самое право загнать на этой же строке))
