### ISSUE TITLE
Изменения в личном кабинете 300

### ISSUE THREAD

**Issue by dropt22** [Crowdfunding-crypto/forum#25]
![123](https://cloud.githubusercontent.com/assets/7222200/5682983/8d6a6942-983d-11e4-85e1-655413aa9cdf.jpg)

**Comment by freepad** [comment]
Сделано
![2015-01-10 01-56-52](https://cloud.githubusercontent.com/assets/3172415/5688762/2e9b051e-986c-11e4-90cc-e590c39db34f.png)
