### ISSUE TITLE
кнопка "Создать проект" съехала

### ISSUE THREAD

**Issue by dropt22** [Crowdfunding-crypto/forum#26]
На крайняк сделай слева через строку.

![111](https://cloud.githubusercontent.com/assets/7222200/5683050/3c1e6d8a-983e-11e4-806e-e9307b49d104.jpg)

**Comment by freepad** [comment]
Тебе нужно очистить кеш, чтобы стили обновились
![easyprey org screen capture 2015-01-09_20-20-38](https://cloud.githubusercontent.com/assets/3172415/5683945/2a3d2ee0-983d-11e4-8d80-4b754793f48f.png)
