### ISSUE TITLE
Убрать значок вордпресса 100

### ISSUE THREAD

**Issue by dropt22** [Crowdfunding-crypto/forum#27]
![1234](https://cloud.githubusercontent.com/assets/7222200/5683240/ad85fc44-983f-11e4-855f-b3df77acb1b5.jpg)

**Comment by freepad** [comment]
![easyprey org screen capture 2015-01-09_20-27-49](https://cloud.githubusercontent.com/assets/3172415/5684022/0093247c-983e-11e4-9f3b-163c7b022c7f.png)
