### ISSUE TITLE
Еще изменения 400

### ISSUE THREAD

**Issue by dropt22** [Crowdfunding-crypto/forum#29]
Дамир, привет! Есть хорошие новости: сделали валюту!) Продолжаем движение.
Как у тебя дела с сессией?

порция новых исправлений:
1)на главной странце убрать слово "форум" 
2)там же убираем всю колонку "свежесть" (только на главной)
3) делаем шрифт крупнее в названии тем, особенно крупно на главной странице
4) как в профиле менять фото аккаунта?
5) когда пишем содержание в посте и используем функцию "ссылка" - она не работает. не показывает слово замещающее ссылку
6) надо создать в личном кабинете на главной странице еще два поля, которые будет заполнять пользователь
номер кошелька (пример :  NXT-YQC6-Y5UF-HYP6-DW8MA)
и публичный ключ (65e55e8687d0776eb2426639c1e4b970e346f55b942b126596197845f93b015d)
7) создать только колонку "Номер кошелька " в настройках пользователей, там же где колонку "сайт" создали

**Comment by freepad** [comment]
Привет. Отлично. С сессией у меня не так хорошо, но тоже продвигается.

**Comment by freepad** [comment]
1. Убрал
2. Убрал
3. Увеличил
4. http://easyprey.org/members/admin/profile/change-avatar/
5. Редактор у тебя спрашивает ссылку (href="") и заголовок (title="'), а слово внутри ссылки не спрашивает.
6. Создал
7. Добавил

**Comment by freepad** [comment]
Насчёт 5, можешь посмотреть на том же toster.ru ссылки вставляются аналогично, только title не вводишь
